### ISSUE TITLE
Is this bundle still maintained? Support for Symfony 3?

### ISSUE THREAD

**Issue by JHGitty** [mmoreram/RSQueueBundle#18]
Is this bundle still maintained? What's about support for Symfony 3?

If this bundle is not maintained anymore there should be a deprecation warning on the repository and on packagist.

**Comment by mmoreram** [comment]
Why do you think this bundles is not maintained anymore?

**Comment by JHGitty** [comment]
Just a question, the last commit was on November 2014. In this list somebody says that this bundle has no support for Symfony 3 yet:
https://docs.google.com/spreadsheets/d/1GOxJ2lNpLxN12YyZ87Bhsxb0iLAQ7e4UDZbJSly8Sy8/edit?pli=1#gid=0

Could you add support for Symfony 3?

**Comment by mmoreram** [comment]
@JHGitty we will :)

**Comment by mmoreram** [comment]
@vguardiola can you check if this bundle is already compatible with Symfony3? (just check that there are no deprecated stuff)

**Comment by mmoreram** [comment]
Closing, because it already is :)
